### PR TITLE
Fix incorrect signature for HTMLCanvasElement.toBlob

### PR DESCRIPTION
**Pull request by elisee**
See #104.

### CODE REVIEW

**Comment by zhengbli** [comment]
:+1: Thanks @elisee

**Comment by rfvyhn** [comment]
Hi, how do I get correct signature in typescript 1.8/2.0?

I found the relevant issues are closed, the milestone in typescript project pinned at 1.8

I do `npm install typescript@beta -D` with npm 6.3.1

and get below in terminal

```
├─┬ typedoc@0.4.5
│ └── typescript@1.8.10
└── typescript@2.0.0
```

in package.json `"typescript": "^2.0.0",`

and tsconfig
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "ES5",
    "removeComments": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "sourceMap": true,
    "noFallthroughCasesInSwitch": true
  },
  "exclude": [
    "node_modules",
    "dist",
    "demo"
  ]
}
```

I open vscode still get

image

do I something wrong?

**Comment by zhengbli** [comment]
Did you set the "typescript.tsdk" option is vscode settings to the ts 2.0 lib folder you installed via npm? Otherwise vscode would use the compiler it has as default, which is 1.8

**Comment by rfvyhn** [comment]
many thanks!!!

resolved by setting `.vscode/setting.json`

```
// 將您的設定放入此檔案中以覆寫預設值和使用者設定。
{
  "typescript.tsdk": "/Users/pleasurazy/.nvm/versions/node/v6.3.1/lib/node_modules/typescript/lib"
}
```

**Pull request merged**
