### PR TITLE
Add kid to JsonWebKey definition

### PR DESCRIPTION
**Pull request by funkybob**
This is to address https://github.com/Microsoft/TypeScript/issues/26854

### CODE REVIEW

**Comment by sandersn** [comment]
@funkybob you need to commit the generated code in addition to the widl change.

**Comment by HolgerJeromin** [comment]
Thanks for jumping in.
This is not in the widl from upstream.
So the [correct place](https://github.com/Microsoft/TSJS-lib-generator#input-files) would be the addTypes.json

**Comment by funkybob** [comment]
@sandersn I honestly don't know how to make the "generated code"... I ran into this problem when trying to migrate a project to TypeScript, figured I'd trying to solve it, and got this far before I ran out of time to contribute, and worked around it locally.

**Comment by sandersn** [comment]
It's `npm run build` and then you diff `baseline` and `generated`. If it looks right, then you run `npm run baseline-accept`.

**Comment by saschanaz** [comment]
Looks like this is not in the WebCrypto spec. [Filing an issue there](https://github.com/w3c/webcrypto/issues) may help. (Reposting from https://github.com/Microsoft/TypeScript/issues/26854#issuecomment-430450762)

**Comment by sandersn** [comment]
Sounds like we should close this here then.

**Comment by pranjaldaffodil** [comment]
Can't believe nobody bothered to report this to W3C in 8 years! I have opened https://github.com/w3c/webcrypto/issues/427 now

**Comment by pranjaldaffodil** [comment]
@sandersn what's the process once WebCrypto updates it on their side?

**Comment by saschanaz** [comment]
It will be automatically updated as the crawled spec data is served by [`@webref/idl`](https://www.npmjs.com/package/@webref/idl)

**Comment by pranjaldaffodil** [comment]
> It will be automatically updated as the crawled spec data is served by [`@webref/idl`](https://www.npmjs.com/package/@webref/idl)

What about adding an interface for JWK Set? It should be relatively simple to create, but will that also require changes in WebCrypto spec?

I noticed that not just `kid` but there were even more missing parameters/attributes and have added them to the above mentioned issue.

**Comment by saschanaz** [comment]
Not being in the spec implies not being in browser implementations, so yes

**Pull request closed without merging**
