### PR TITLE
To fix #4550

### PR DESCRIPTION
**Pull request by plantain-00**
https://github.com/Microsoft/TypeScript/issues/4550

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by zhengbli** [comment]
:+1:

**Comment by elisee** [comment]
I believe the function signature is wrong, `toBlob()` is async and takes a callback and media type according to https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by mhegazy** [comment]
@elisee do you mind filling a new issue for this?

**Comment by elisee** [comment]
@mhegazy sure, done!

**Pull request merged**
