### PR TITLE
Add types to key wrapping and unwrapping

### LINKED ISSUE #636: Add types to key wrapping and unwrapping
Currently, it is impossible to wrap and unwrap keys in Typescript as the algorithm parameters are not possible under the current type definitions. 

PR: https://github.com/Microsoft/TypeScript/pull/29342

### PR DESCRIPTION
**Pull request by JamesJansson**
Currently, it is impossible to wrap and unwrap keys in Typescript as the algorithm parameters are not possible under the current type definitions. I have used the examples of wrap and unwrap from here:
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/unwrapKey
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/wrapKey

I may have gone overboard a little with including "RsaKeyAlgorithm | RsaHashedKeyAlgorithm" however the following assumes that those types are necessary:
https://github.com/diafygi/webcrypto-examples

closes #636

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
If you add "closes #636" into your comment the issue will be closed on merge by the github infrastructure.

**Comment by sandersn** [comment]
@JamesJansson looks like you need to run `npm run baseline-accept` to get tests to pass.

**Comment by orta** [comment]
Hey @JamesJansson  - we've looking through the backlog, I've updated the PR to master (and updated baselines) but we need both a CLA and the CI is failing. Any chance you can take a look at the CLA and give me an opinion on the CI?

**Comment by sandersn** [comment]
This PR hasn't seen any activity for quite a while, so I'm going to close it to keep the number of open PRs manageable. Feel free to open a fresh PR or continue the discussion here.

**Pull request closed without merging**
