### PR TITLE
Add missing optional constructor param for Text

### PR DESCRIPTION
**Pull request by alexeagle**
/cc @samccone

### CODE REVIEW

**Comment by SaschaNaz** [comment]
[The file must not be modified](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/README.md):
image

**Comment by alexeagle** [comment]
Thanks - in that case, what is the mechanism to change the lib.dom.d.ts
that is distributed with TypeScript? Does it require a change to Edge where
this IDL originates?

**Comment by SaschaNaz** [comment]
You'll want to look at addedTypes.json to add a constructor to an interface.

**Comment by SaschaNaz** [comment]
Make sure you get `pass` on the build script to solve the CI failure! The `generated` directory will have new files and you have to copy-paste them to `baselines` directory.

**Comment by alexeagle** [comment]
The CI only says that the generated file doesn't match the baseline, without printing the diff. I guess I'll have to install Mono so I can generate the files locally.

**Comment by alexeagle** [comment]
Thanks for the help @SaschaNaz !

**Comment by samccone** [comment]
Thanks @alexeagle

**Comment by mhegazy** [comment]
Link to documentation: https://dom.spec.whatwg.org/#text

For future purposes, please file an issue on the TS repo along with the change.

**Comment by mhegazy** [comment]
thanks!

**Comment by mhegazy** [comment]
and thanks @SaschaNaz!

**Comment by samccone** [comment]
thank you for landing @mhegazy

**Pull request merged**
