### PR TITLE
Add "| boolean" to pixelStorei method parameter

### PR DESCRIPTION
**Pull request by VStas**
For issue (https://github.com/Microsoft/TypeScript/issues/13093)

### CODE REVIEW

**Comment by VStas** [comment]
Hmm, I signed the CLA, not sure why the bot is not reacting

**Comment by VStas** [comment]
@mhegazy

**Comment by mhegazy** [comment]
@VStas can you please sign the CLA?

**Comment by mhegazy** [comment]
also, this change seems to break checking the library, can you look into that as well?

**Comment by mhegazy** [comment]
never mind that, i think the test is already broken. looking into it.

**Comment by mhegazy** [comment]
tests are passing now. we just need the CLA.

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Pull request merged**
