### PR TITLE
update types rejection handled

### PR DESCRIPTION
**Pull request by vkrbt**
fixes https://github.com/microsoft/TypeScript/issues/34511

### CODE REVIEW

**Comment by vkrbt** [comment]
Hi, I noticed that all check were passed, could this code be merged? I need this fix in my code
Thanks a lot!

**Comment by saschanaz** [comment]
@orta?

**Comment by orta** [comment]
👍 yep, looks like it's correct to the spec

**Comment by orta** [comment]
I think it could be too late to get it into the 3.7 RC though

**Pull request merged**
