### PR TITLE
TypeScript Issue # 18615.

### PR DESCRIPTION
**Pull request by muj-beg**
Added `DOMRect`, `DOMRectReadOnly` and `DOMRectList` types.  Modified signatures of properties/methods that used `ClientRect` or `ClintRectList` types to use `ClientRect | DOMRect` or `ClintRectList | DOMRectList` types respectively. (Left some MS/IE/Edge specific methods/properties unchanged)

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
ref https://github.com/Microsoft/TypeScript/issues/18615

**Comment by mhegazy** [comment]
@muj-beg  can you please refresh this PR.

**Comment by muj-beg** [comment]
@mhegazy PR updated.

**Comment by SaschaNaz** [comment]
Tip: `git pull --rebase Microsoft master` is great!

**Comment by timocov** [comment]
@muj-beg why added interfaces is without `"flavor": "DOM"` property? Seems that is DOM-only types.

**Comment by muj-beg** [comment]
@timocov I've added the `flavor: DOM` to these and merged in latest changes.
(Sorry, my merge history is a mess -- I realize I should have likely done a rebase.  I'll keep that in mind for next time.)

**Pull request merged**
