### PR TITLE
Remove MSStreamReader/WebKitFileSystem related types

### PR DESCRIPTION
**Pull request by saschanaz**
~~`prune()` now filters based on common simple rule: `propertyname: null` means *remove `propertyname`*. This enables removing interface declarations.~~ (was a part of #445)

### CODE REVIEW

**Comment by mhegazy** [comment]
@saschanaz are you planning on updating this PR?

**Comment by mhegazy** [comment]
thanks!

**Comment by mhegazy** [comment]
@saschanaz are you planning on adding more specs?

**Comment by saschanaz** [comment]
I've been busy for some other works but yes.

**Pull request merged**
