### PR TITLE
add MouseWheelEvent

### PR DESCRIPTION
**Pull request by YuichiNukiyama**
fix #[9071](https://github.com/Microsoft/TypeScript/issues/9071).

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
had a chat with @zhengbli offline, this should be added to addedTypes instead.

something like:

```ts
{
        "kind": "typedef",
        "flavor": "Worker",
        "name": "MouseWheelEvent",
        "type": "WheelEvent"
}, 
```

**Comment by YuichiNukiyama** [comment]
@mhegazy Ah, I don't know we can generate types! Thanks.

**Comment by zhengbli** [comment]
:+1: Thanks!

**Pull request merged**
