### PR TITLE
Update Mailmap

### PR DESCRIPTION
**Pull request by nrcoley**
Hi - I'd really appreciate it if this PR could be merged in to update my email address in the mailmap. I'd feel more comfortable if this information was less easily available. Thanks!

### CODE REVIEW

**Comment by mhegazy** [comment]
This file is generated from the git commit history. i am happy to remove your name altogether, but it does not change the git history.

**Comment by nrcoley** [comment]
Hi @mhegazy I understand that it does not change the commit history - I'm just hoping to reduce how easy it is to access. If you could remove my name altogether that would be great, currently it comes up pretty quickly with a google search of that email (which leads to this mailmap, as well as the one for the Typescript repo that I was about to make a similar PR for) which is what I'm hoping to reduce. Thanks!

**Comment by mhegazy** [comment]
can you remove the entry altogether then.

**Comment by nrcoley** [comment]
Yes, sorry, thanks, just updated the PR.

**Pull request merged**
