### PR TITLE
specify return type for querySelector

### PR DESCRIPTION
**Pull request by YuichiNukiyama**
fix [querySelector return type could be more specific for single-element selectors #8114](https://github.com/Microsoft/TypeScript/issues/8114)

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by zhengbli** [comment]
Thanks @YuichiNukiyama !

**Comment by yuttie** [comment]
@YuichiNukiyama Thanks for your great work.

I found I cannot select an `SVGTitleElement` (https://developer.mozilla.org/en-US/docs/Web/API/SVGTitleElement) by querying "title" with SVGSVGElement's `querySelector()`.  I think the problem is related to this PR.

I think it would be nice if `querySelector("title")` returns a value of type `HTMLTitleElement | SVGTitleElement`.

How do you think?

**Comment by YuichiNukiyama** [comment]
@yuttie 
A good point. However, cast is necessary, so it is hard to use.

**Pull request merged**
