### PR TITLE
Remove 'prerender' from document VisibilityState

### PR DESCRIPTION
**Pull request by kripod**
Resolves https://github.com/microsoft/TypeScript/issues/31957

### CODE REVIEW

**Comment by saschanaz** [comment]
`npm run build && npm run baseline-accept` should be done to fix the test.

**Comment by kripod** [comment]
> `npm run build && npm run baseline-accept` should be done to fix the test.

Unfortunately, I get the following issues when running those commands:

```
> npm run build && npm run baseline-accept

> tsjs-lib-generator@ build D:\Development\Projects\TSJS-lib-generator
> tsc --p ./tsconfig.json && node ./lib/index.js

node_modules/@types/node/index.d.ts:74:11 - error TS2300: Duplicate identifier 'IteratorResult'.

74 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:74:11
    74 interface IteratorResult<T> { }
                 ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
```

**Comment by kripod** [comment]
@saschanaz Unfortunately, I get the following issues when running those commands:

```
> npm run build && npm run baseline-accept

> tsjs-lib-generator@ build D:\Development\Projects\TSJS-lib-generator
> tsc --p ./tsconfig.json && node ./lib/index.js

node_modules/@types/node/index.d.ts:74:11 - error TS2300: Duplicate identifier 'IteratorResult'.

74 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:74:11
    74 interface IteratorResult<T> { }
                 ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
```

**Comment by saschanaz** [comment]
Try rebasing + `npm i` and do it again, as it's fixed in https://github.com/microsoft/TSJS-lib-generator/pull/737.

**Comment by kripod** [comment]
@saschanaz Thanks for the tip, everything seems to work now.

**Comment by kripod** [comment]
@saschanaz I just recreated the entire PR with a force push to avoid issues.

**Comment by kripod** [comment]
@saschanaz Sorry for interrupting, but may I ask if there is anything I may help with to get this PR merged?

**Comment by saschanaz** [comment]
Pinging @sandersn

**Comment by kripod** [comment]
@saschanaz @sandersn I'm sorry to disturb again, but may I ask if there are any blocking factors to resolve regarding this PR?

**Comment by saschanaz** [comment]
Pinging @orta this time ..

**Comment by sandersn** [comment]
Thanks for your patience! It's been a busy release.

**Comment by qinyuhang** [comment]
I'm sorry but I failed to see why U remove `prerender`, It's still on in MDN https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState

**Comment by kripod** [comment]
@qinyuhang It’s marked as deprecated and has already been removed from the corresponding spec.

**Comment by HolgerJeromin** [comment]
I marked it as deprecated in MDN.

**Pull request merged**
