### PR TITLE
add PromiseRejectionEvent from WHATWG Living Standard

### PR DESCRIPTION
**Pull request by tuures**
https://github.com/Microsoft/TypeScript/issues/10297

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by zhengbli** [comment]
👍

**Comment by epicgirl1998** [comment]
i think it's missing the `declare var PromiseRejectionEvent` part

```typescript
function getErrorEventText (event: ErrorEvent | PromiseRejectionEvent) {
	
	if (event instanceof ErrorEvent) {
		return event.message;
	}
	
	// [ts] 'PromiseRejectionEvent' only refers to a type, but is being used as a value here.
	if (event instanceof PromiseRejectionEvent) {
		return String(event.reason);
	}
	
	return "<unknown error>";
	
}
```

i had to put this in my code (modified from `ErrorEvent`):

```typescript
declare var PromiseRejectionEvent: {
    prototype: PromiseRejectionEvent;
    new(type: string, promiseRejectionEventInitDict?: PromiseRejectionEventInit): PromiseRejectionEvent;
}
```

**Comment by zhengbli** [comment]
Hi @epicgirl1998 do you mind send another PR to fix this! Help is appreciated. Thank you!

**Comment by epicgirl1998** [comment]
i would like to contribute but i can't seem to find any documentation for the input json files (how do all the other contributors know what to do? or am i just missing something?)

**Comment by zhengbli** [comment]
The general overview is at https://github.com/Microsoft/TSJS-lib-generator/blob/master/README.md
You can refer to json format used by other types in the json file to figure out what you need to add. 

For this case, I think it should be sufficient to add a `"constructorSignatures"` to this json. Similar example can be found at:
https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/addedTypes.json#L184

**Pull request merged**
