### PR TITLE
Removed duplicate "the" from documentation

### PR DESCRIPTION
**Pull request by PunKeel**
https://github.com/Microsoft/TypeScript/issues/27528

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Thanks!

**Comment by saschanaz** [comment]
`*.commentmap.json` must not be hand-written as it will then be overwritten by `npm run fetch`. This specific case has been fixed in the upstream (whatwg/fetch#822), though.

**Comment by DanielRosenwasser** [comment]
Good call, we should really have `.generated` or `.external` in the name then.

**Comment by saschanaz** [comment]
Actually anything in `inputfiles/idl` shouldn't be hand-written 😀

I filed #602 to prevent this in CI level, but it seems the readme should also be updated as currently it only says about `browser.webidl.json`.

**Pull request merged**
