### PR TITLE
Fix IDBIndex interface for openCursor/openKeyCursor

### PR DESCRIPTION
**Pull request by falsandtru**
issue: https://github.com/Microsoft/TypeScript/issues/7218

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
See my comment on https://github.com/Microsoft/TypeScript/issues/7218#issuecomment-188668347.

**Comment by falsandtru** [comment]
@mhegazy @DanielRosenwasser @zhengbli can you merge this fix?

**Comment by zhengbli** [comment]
@falsandtru I just noticed this change is covered by #72 , which is a bigger change that updates the XML spec file.

**Comment by falsandtru** [comment]
Oh nice update. I follow your fixes.

**Pull request closed without merging**
