### PR TITLE
Add build to Travis

### PR DESCRIPTION
**Pull request by myitcv**
Also includes a couple of tweaks to `build.sh` 

https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html

```
set -e === set -o errexit
set -u === set -o nounset
```

### CODE REVIEW

**Comment by myitcv** [comment]
You can see the result of the build in my personal fork here:

https://travis-ci.org/myitcv/TSJS-lib-generator/builds/122091879

**Comment by zhengbli** [comment]
Why do we need to two CI systems? What is that Travis can do and AppVeyor can't?

**Comment by myitcv** [comment]
@zhengbli because AppVeyor is, to my knowledge, only Windows-based. Given that this package is not Windows platform specific (indeed cross platform steps are listed) it makes sense to include a CI build for *nix platforms to check that the documented build/run steps work on platforms other than Windows.

**Comment by myitcv** [comment]
@zhengbli any update on whether you want to merge this or not?

**Comment by zhengbli** [comment]
@myitcv sorry for the delay ... let me rerun the CI and set up travis.

**Comment by zhengbli** [comment]
Added the build script and status badge in readme. Thanks @myitcv !

**Pull request merged**
