### PR TITLE
try to fix https://github.com/Microsoft/TypeScript/issues/8101

### PR DESCRIPTION
**Pull request by plantain-00**
Fixes https://github.com/Microsoft/TypeScript/issues/8101

### CODE REVIEW

**Comment by mhegazy** [comment]
I left a comment about the return type in https://github.com/Microsoft/TypeScript/issues/8101#issuecomment-219497942. it will address the original issue, but will make clearer (i think :)).

**Comment by mhegazy** [comment]
let's change the return type from `any` to `void`, and we should be good to go.

**Comment by plantain-00** [comment]
Sorry for delay, a little busy.

**Comment by mhegazy** [comment]
thanks! might want to add a similar change to setImmediate as well.

**Comment by sandersn** [comment]
Shouldn't the new overload be first since it's more specific?  Otherwise I think the compiler will still always choose the original overload.

**Comment by plantain-00** [comment]
Since `setImmediate` will need a similar overload as `setTimeout`, what about `setInterval`? a similar overload too?

**Comment by mhegazy** [comment]
sounds about right.

**Pull request merged**
