### PR TITLE
Add HTMLTemplateDocument

### PR DESCRIPTION
**Pull request by dashaus**
Fix https://github.com/Microsoft/TypeScript/issues/5199

### CODE REVIEW

**Comment by dashaus** [comment]
But I need to add the following, right?:

```typescript
declare var HTMLTemplateElement: {
  prototype: HTMLTemplateElement;
  new(): HTMLTemplateElement;
}
```

But I don't know how do it by addedTypes.json... :(

**Comment by zhengbli** [comment]
@dashaus I'm adding support for those. Will keep you updated.

**Comment by dashaus** [comment]
:+1:

**Comment by zhengbli** [comment]
@dashaus The new bit is merged in. So to add constructors, you need to add a `constructorSignatures` string array property to your json object. Also, as this is a DOM type that should not be added to webworker definition, you may want to add a `flavor` property that has the value `Web`.

Your added json content should be something like:
```
    {
        "kind": "interface",
        "name": "HTMLTemplateElement",
        "flavor":  "Web",
        "extends": "HTMLElement",
        "constructorSignatures": [
            "new(): HTMLTemplateElement"
        ],
        "properties": [
            {
                "name": "content",
                "type": "DocumentFragment"
            }
        ]
    }
```

**Comment by dashaus** [comment]
Something I did wrong ... I'm a newbie with git ... :(

I created a new pull request

**Pull request closed without merging**
