### PR TITLE
Add currentScript property to interface Document

### PR DESCRIPTION
**Pull request by dashaus**
Fix https://github.com/Microsoft/TypeScript/issues/5533

### CODE REVIEW

**Comment by zhengbli** [comment]
@dashaus Hello! As the `dom.generated.d.ts` is auto generated by a script, to update it you need to make several changes to make the test pass:
1. Add the missing element to `inputfiles/addedTypes.json`, or overriding element to `inputfiles/overridingTypes.json`, or elements to remove to `inputfiles/removedTypes.json` 
2. Run the script locally to obtain new `dom.generated.d.ts` and `webworker.generated.d.ts`
3. Update the baselines in the `baselines` folder using the newly generated files

Then the CI will first check if the generated files match the baselines, and then if all compiler tests pass using the newly generated files.

**Comment by zhengbli** [comment]
Aha you are already doing it. Kudos! I'll just keep the comment for future references.

**Comment by dashaus** [comment]
Thanks you! And I'm Sorry, I'm a newbie at this... The test fails, but I did not follow instructions correctly... I have a question: The script is possible execute it from OS X? I use this SO so I don't know if it is possible...

**Comment by zhengbli** [comment]
No worries! I just found the CI server has some problems too. 
And It is possible to build on OSX. Let me try adding support for OS X build today.

**Comment by dashaus** [comment]
Ok, nice! Thanks you!

**Comment by zhengbli** [comment]
@dashaus OK not it should be done. Although to run it you need to install mono 4.2 from:
http://www.mono-project.com/download/alpha/

And then you can just run `./build.sh`

**Comment by zhengbli** [comment]
Although I think in this case the reason why generated script is different from the baseline is the added comment. You can either change the `inputfiles/comment.json` as well, or just not adding comment.

**Comment by dashaus** [comment]
Ok, I deleted the comment, but I go to use the script for add the comment in `comment.json`

**Comment by dashaus** [comment]
The test fails so I go to try do it following the instructions!

**Comment by dashaus** [comment]
I clone the repo, I add to the end of file in `addedTypes.json` the below code:

```json
{
        "link": "property",
        "interface": "Document",
        "name": "currentScript",
        "type": "HTMLScriptElement"
}
```

Finally, run `./build.sh` and the test is ok:

```
No version specified. Downloading latest stable.
Paket.exe 2.22.2 is up to date.
Paket version 2.22.2.0
0 seconds - ready.
Building project with version: LocalBuild
Shortened DependencyGraph for Target Test:
<== Test
   <== Run

The resulting target order is:
 - Run
 - Test
Starting Target: Run 
Finished Target: Run
Starting Target: Test (==> Run)
All tests passed.
Finished Target: Test

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Run        00:00:05.9778622
Test       00:00:00.0285978
Total:     00:00:06.0578896
Status:    Ok
---------------------------------------------------------------------
```

But the `dom.generated.d.ts` file is exactly equal than the `baselines` file.

Are I doing something wrong?

**Comment by zhengbli** [comment]
@dashaus in the Json file it should be "kind" instead of "link" I think

**Comment by dashaus** [comment]
Ajam! Now the test fails but the file generated include the currentScript...

Is It because the generated file is different to same file of baselines folder, right?

```
Building project with version: LocalBuild
Shortened DependencyGraph for Target Test:
<== Test
   <== Run

The resulting target order is:
 - Run
 - Test
Starting Target: Run 
Finished Target: Run
Starting Target: Test (==> Run)
Running build failed.
Error:
System.Exception: 
Test failed: dom.generated.d.ts is different from baseline file.
   at FSI_0001.Build+clo@24-1.Invoke (Microsoft.FSharp.Core.Unit _arg1) in <filename unknown>:line 0
   at Fake.TargetHelper+targetFromTemplate@195[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) in <filename unknown>:line 0
   at Fake.TargetHelper.runSingleTarget (Fake.TargetTemplate`1 target) in <filename unknown>:line 0

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Run        00:00:05.9406188
Total:     00:00:06.0263224
Status:    Failure
---------------------------------------------------------------------
  1) System.Exception: 
Test failed: dom.generated.d.ts is different from baseline file.
   at FSI_0001.Build+clo@24-1.Invoke (Microsoft.FSharp.Core.Unit _arg1) in <filename unknown>:line 0
   at Fake.TargetHelper+targetFromTemplate@195[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) in <filename unknown>:line 0
   at Fake.TargetHelper.runSingleTarget (Fake.TargetTemplate`1 target) in <filename unknown>:line 0
---------------------------------------------------------------------
```

**Comment by zhengbli** [comment]
Right, from the error message: `Test failed: dom.generated.d.ts is different from baseline file.` :)
So do you still see the tests fail if you update the baseline files accordingly?

**Comment by dashaus** [comment]
Ok, I copy the generated file to `baselines` folder and the tests is ok, but including the comment in comments.json does not effect... it is not included in the generated file.

**Comment by zhengbli** [comment]
@dashaus My bad that the comment now is not picked up. Though you can just send PR without the comments. I'll add the part later.

**Pull request closed without merging**
