### PR TITLE
Add missing HTML tags

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes Microsoft/TypeScript#17828

### CODE REVIEW

**Comment by falsandtru** [comment]
@sandersn Merge this plz. I need this patch.

**Comment by inad9300** [comment]
It's not *too* bad to merge this... since it is an improvement. But it is not yet close to fixing https://github.com/Microsoft/TypeScript/issues/17828:
- The HTML elements `details` and `dialog` haven't been included.
- The new HTML interfaces added by @arjunyel (`HTMLMainElement`, `HTMLDetailsElement`, etc.), as mentioned in the comments, have been ignored.
- The SVG elements mentioned in the comments (`a`, `script`, `style`, and `title`) haven't been considered.

In my opinion, these changes should be reverted until every point is tackled, or else it will be extra work to verify what is and what isn't done.

**Comment by saschanaz** [comment]
Hi @inad9300, those HTML tags are covered by other PRs and included in master branch: https://raw.githubusercontent.com/Microsoft/TSJS-lib-generator/master/baselines/dom.generated.d.ts

The SVG elements is related with https://github.com/Microsoft/TSJS-lib-generator/issues/582#issuecomment-430437141. We currently can't add them because of the blocker.

**Comment by inad9300** [comment]
Hi @saschanaz. Thanks for following up this issue and for finally resolving the problem with `ElementTagNameMap`. Nevertheless, please do use the more specific interfaces for the newly added elements, such as `HTMLMainElement` and the others.

**Comment by saschanaz** [comment]
> please do use the more specific interfaces for the newly added elements, such as HTMLMainElement and the others.

There is no HTMLMainElement in the standard. The interface in current lib.d.ts should be removed instead.

________________________________

**Comment by inad9300** [comment]
Great then! Sorry for the inconvenience caused.

**Pull request merged**
