### PR TITLE
Add Web Share types

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes https://github.com/microsoft/TypeScript/issues/18642.

### CODE REVIEW

**Comment by orta** [comment]
Thanks @saschanaz

**Comment by Artur-** [comment]
The suggestion in the linked issue suggests adding
```
interface Navigator {
  share?: NavigatorShare;
}
```

however this PR adds it as
```
interface Navigator {
  share: NavigatorShare;
}
```

As `share` is not available in most browsers, you want to check for the existence of it before using it but
```
if (navigator.share) {
```

now results in an error
```
This condition will always return true since the function is always defined. Did you mean to call it instead? ts(2774)
```

**Comment by samtgarson** [comment]
@orta This comment 👆 seems correct, is there a reason `share` is always defined here?

**Comment by orta** [comment]
That is how the w3c spec defines it- you're welcome to send a PR making it optional 👍🏻

**Comment by ferm10n** [comment]
any reason why `canShare` wasn't added as well?

**Comment by saschanaz** [comment]
It's added later by #1125.

**Pull request merged**
