### PR TITLE
Add HTMLTemplateDocument

### PR DESCRIPTION
**Pull request by dashaus**
Fix https://github.com/Microsoft/TypeScript/issues/5199

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
@zhengbli can we get this in?

**Comment by zhengbli** [comment]
@mhegazy We can for now, but I found that many of the similar interfaces (HTMLxxxElement) doesn't actually have a legal constructor, while my script generates constructors for them because at the time I thought it would be consistent with the old version (before the script) and reduce breaking changes. Although I think we probably should remove them all together at some point.

**Comment by mhegazy** [comment]
if we remove the constructors we break `instanceof` checks. so we need another solution here.

**Comment by zhengbli** [comment]
In that case we can take this change now which solves this particular issue, and then figure out how to deal with the constructors systematically later.

**Comment by zhengbli** [comment]
@dashaus Thansk for your contribution :)

**Pull request merged**
