### PR TITLE
Fix event types of XMLHttpRequest

### PR DESCRIPTION
**Pull request by falsandtru**
Fixes https://github.com/Microsoft/TypeScript/issues/8691

### CODE REVIEW

**Comment by falsandtru** [comment]
How can I override `addEventListener` signatures?

**Comment by falsandtru** [comment]
@zhengbli Are you supported signature overriding like this?

**Comment by mhegazy** [comment]
ping @zhengbli

**Comment by zhengbli** [comment]
Overriding the signatures of `addEventListener` is tricky because the way string overloads works in TypeScript. The overload signature may come from the spec, or inherited from base classes. However if it has its own overload signatures, all inherited ones will be wiped. So the normal way of overriding properties may not work properly here. I'll come up with a fix shortly.

**Comment by falsandtru** [comment]
Any updates?

**Comment by zhengbli** [comment]
Actually I found it is easier to change the emitting F# code. I sent another PR at https://github.com/Microsoft/TSJS-lib-generator/pull/144, sorry for the delay.

**Comment by falsandtru** [comment]
LGTM 👍

**Pull request closed without merging**
