### PR TITLE
WebSpeech's SpeechRecognition onerror incorrectly reports ErrorEvent as event

### PR DESCRIPTION
**Pull request by shareefalis**
See: https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionErrorEvent

### CODE REVIEW

**Comment by shareefalis** [comment]
For a more robust implementation. `SpeechRecognitionErrorEvent` type has to be implemented 

Reference: https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionErrorEvent

**Comment by saschanaz** [comment]
`ErrorEvent` has nothing to do with `SpeechRecognitionErrorEvent`. This is done because no browser implements the interface.

**Comment by sandersn** [comment]
It's OK, I guess, to use a different subtype that's "close enough". I'm not a huge fan, but I appreciate that default is easy even if it's not correct.

In the event that `SpeechRecognitionErrorEvent` is implemented, the PR that switches `ErrorEvent` to `SpeechRecognitionErrorEvent` will need to find and refer to this PR to explain why it's the right change.

**Comment by saschanaz** [comment]
@sandersn Despite the name, `SpeechRecognitionErrorEvent` has no `filename`, `lineno`, `colno` etc. and thus can confuse users more.

**Comment by sandersn** [comment]
@orta and I had a hard time deciding, but it seems like the choice is basically between a type with too many properties, `ErrorEvent` and a type with too few, `Event`. `ErrorEvent` is actually an unrelated subtype of `Event`, but that's mainly confusing to maintainers.

I went with the too-large type because it at least provides `error` and `message` even if `filename/lineno/colno` are also mistakenly present. If you feel strongly about this I will revert it.

**Comment by saschanaz** [comment]
That rationale sounds reasonable. Since the names of the extra properties strongly suggests they are irrelevant here, I don't oppose here. Thanks for the details behind the decision 👍

**Pull request merged**
