### PR TITLE
Proposed fix for issue 501

### PR DESCRIPTION
**Pull request by stevedorries**
Adds proposed function signature overload.

### CODE REVIEW

**Comment by mhegazy** [comment]
You need to also include the generated baseline

**Comment by stevedorries** [comment]
Generated baseline is now included.

**Comment by mhegazy** [comment]
Sorry i merged that too fast. i think there is one more change needed.. instead of using `"additional-signatures"` use `"override-signatures"` to avoid having the extra signature at the bottom.

**Comment by HolgerJeromin** [comment]
Ref #501

**Pull request merged**
