### PR TITLE
Add property of AudioContext state API

### PR DESCRIPTION
**Pull request by rixrix**
Hi

This fixes https://github.com/Microsoft/TypeScript/issues/5816

This is my first PR, would be good if someone can give feedback. thanks

### CODE REVIEW

**Comment by mhegazy** [comment]
the webidl files are not supposed to change. please see https://github.com/Microsoft/TSJS-lib-generator#contribution-guide for how you can augment definitions.

**Comment by rixrix** [comment]
@mhegazy great, I'll look into it. thanks

**Comment by rixrix** [comment]
@mhegazy if you could look at it again, that'd be great. Previous change set was definitely a mistake. cheers

**Comment by mhegazy** [comment]
:+1:

**Comment by zhengbli** [comment]
:+1:  Thanks for the contribution @rixrix !

**Pull request merged**
