### PR TITLE
add currentScript to Document

### PR DESCRIPTION
**Pull request by dashaus**

### CODE REVIEW

**Comment by dashaus** [comment]
I did another fork for get the OS X support from last pull request and finally the test (in my computer) is ok.

**Comment by dashaus** [comment]
The checks have passed! I remove .DS_Store.

**Comment by zhengbli** [comment]
Fix Microsoft/TypeScript#5533

@dashaus Thanks! Look good to me

**Comment by mhegazy** [comment]
Yaaay!! First PR to the new repo! :tada: 

Thanks @dashaus

**Comment by dashaus** [comment]
You're welcome! :+1:

**Pull request merged**
