### PR TITLE
Make the `data` property of MessageEvent generic

### PR DESCRIPTION
**Pull request by cawa-93**
Fix https://github.com/microsoft/TypeScript/issues/19370

### CODE REVIEW

**Comment by CKGrafico** [comment]
We have the message "MessageEvent" is not generic when
```
window.addEventListener('message', (event: MessageEvent<CustomDataType>) => {})
```

**Comment by sapter** [comment]
I'm also still getting an error Type `'MessageEvent' is not generic`. @CKGrafico have you been able to resolve this or figure out why we're still getting an error? I'm on TS v4.2.2

**Comment by CKGrafico** [comment]
@sapter nop sorry, there is the worst workaround in the world :'(

```
 window.addEventListener('message', (event: MessageEvent) => {
      const data: PanelMessage = event.data;
```

**Comment by bb-in-hoodie** [comment]
There is no error underline in VSCode, but it keeps yield an error message in terminal when the code gets built.
`Type 'MessageEvent' is not generic.`
Is there no fix yet?

**Comment by saschanaz** [comment]
> There is no error underline in VSCode, but it keeps yield an error message in terminal when the code gets built.
> `Type 'MessageEvent' is not generic.`
> Is there no fix yet?

I think your local TypeScript version is low in that case.

**Comment by bb-in-hoodie** [comment]
> I think your local TypeScript version is low in that case.

since which TS version does support this typing?
I'm on v3.9.6 for now.

210618-04-message_event_TS_error

**Comment by cawa-93** [comment]
> since which TS version does support this typing?

@bb-in-hoodie >= v4

**Comment by bb-in-hoodie** [comment]
Thank you 👍

**Pull request merged**
