### PR TITLE
Add typing for Navigator.getBattery()

### PR DESCRIPTION
**Pull request by Jack-Works**
https://github.com/Microsoft/TypeScript/issues/15314
https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API
https://www.w3.org/TR/battery-status

Signed-off-by: Jack Works <zjwpeter@gmail.com>

### CODE REVIEW

**Comment by noomorph** [comment]
@Jack-Works , isn't it deprecated?

https://www.fxsitecompat.com/en-CA/docs/2016/battery-status-api-has-been-removed/

AFAIK, only privileged apps can use it.

**Comment by Jack-Works** [comment]
Umm...
This API is sound removed.
https://webkit.org/status/#specification-battery-status-api

Edge is considering support this API: http://status.modern.ie/batterystatusapi
Chrome is shipped.
Firefox used to shipped but removed it (unless in privileged code).
Safari does not support this.

So this is a Chrome-Only API now.
But I think this should be added to the navigator.
Maybe I can add some API limited warning on it?

**Comment by mhegazy** [comment]
If this is not a standard feature, nor on the standard track, it should not be included.

**Comment by Jack-Works** [comment]
Alright

**Comment by elasim** [comment]
Here is up to date status.

Draft has been updated recently. (Draft 12 June 2018)
Chrome is shipped long times ago.
Firefox is shipped
WebKit is removed because of privacy matter.

@mhegazy @Jack-Works 
Can we discuss this issue again?

**Comment by Jack-Works** [comment]
I see there is no sign that battery api come back again. According to the principle of lib.d I guess it has no way to merge in.

**Comment by stefann01** [comment]
Why is this not introduced? From what I see it can be used in some browsers, and it is specified in the mdn docs.
https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API
https://caniuse.com/?search=battery.

**Comment by mathe42** [comment]
It is only supported in chromium based browsers (= 1 implementation) but we require 2 implementations to support it to add it. And that will probably not happen (in near future).

---
Chrome, Edge, Opera all the same implementation.

**Pull request closed without merging**
