### PR TITLE
Add typings for custom elements v1 API

### PR DESCRIPTION
**Pull request by rictic**
Source: https://www.w3.org/TR/2016/WD-custom-elements-20160830/

As suggested by comments on https://github.com/Polymer/polymer/pull/3954

### CODE REVIEW

**Comment by zhengbli** [comment]
👍 
Can you resolve the merge conflicts? Thanks

**Comment by rictic** [comment]
Sure thing, rebased!

**Comment by rictic** [comment]
Rebased again!

**Comment by rictic** [comment]
Hm, looks like it was failing due to the use of `Promise`. Changed to PromiseLike as I see other code here using.

**Comment by rictic** [comment]
Erp, hadn't updated the baseline. Amended that commit.

**Pull request merged**
