### PR TITLE
Add Clipboard Interfaces to idlSources

### PR DESCRIPTION
**Pull request by Brcrwilliams**
Update ClipboardEventInit interface to match [the W3C spec](https://www.w3.org/TR/clipboard-apis/#clipboard-event-interfaces).
See Microsoft/TypeScript#28998 for additional information.

### CODE REVIEW

**Comment by saschanaz** [comment]
TS now prefers directly fetching W3C standard rather than manually maintaining types.

I recommend:

1. Add the following item to the `inputfiles/idlSources.json`.

   ```json
   {
     "url": "https://www.w3.org/TR/clipboard-apis/",
     "title": "Clipboard"
   }
   ```
2. Remove `ClipboardEventInit` from `addedType.json` and also `ClipboardEvent` from `overridingTypes.json`.
3. Run `npm run fetch -- Clipboard`
4. Commit the result

**Comment by Brcrwilliams** [comment]
@saschanaz Thank you for the guidance. That approach does sound better. I have applied those changes.

**Comment by sandersn** [comment]
CI is broken from an earlier change. I'll merge again when I've fixed it.

**Comment by saschanaz** [comment]
Looks like something weird happened when merging.

**Pull request merged**
