### PR TITLE
Improve WebAssembly.instantiateStreaming

### PR DESCRIPTION
**Pull request by RReverser**
Follow-up to #755.

### CODE REVIEW

**Comment by RReverser** [comment]
@orta Apologies, this should be the last one.

**Comment by orta** [comment]
👍

**Comment by RReverser** [comment]
@orta thanks :) To duplicate my question from the last PR:

> @orta Thanks! Do you know if I need to do anything further to get definitions updated on the TypeScript side or are they pulled from here automatically on new release?

**Comment by orta** [comment]
Hrm, it looks to me like these changes are then PR'd into the TypeScript repo (maybe this was the last PR doing that - https://github.com/microsoft/TypeScript/pull/32335 )

**Comment by RReverser** [comment]
@orta I see. Do you want / need to do that as a maintainer, or should I?

**Comment by RReverser** [comment]
@orta Sorry, but ping :) Should I do something next?

**Comment by orta** [comment]
Yep, I’d recommend sending a change over to the main repo - otherwise it’ll happen whenever we do an update ourselves

**Pull request merged**
