### PR TITLE
Add IDBValidKey to knownWorkerTypes

### LINKED ISSUE #426: IDBValidKey does not exist in lib.webworker.d.ts
This type exists in DOM types, but does not exist in Web Worker types. It should exist in both, as IndexedDB spec and implementation is the same for both.

It is defined [here](https://github.com/Microsoft/TSJS-lib-generator/blob/818f7457e6bffe0bd8255f4e00f1b1dd700cd425/inputfiles/addedTypes.json#L2876).

### PR DESCRIPTION
**Pull request by mmermerkaya**
Fixes #426

### CODE REVIEW

**Comment by mhegazy** [comment]
you also need to update the baselines. 
```sh
npm run build
npm run baseline-accept
```

**Comment by mhegazy** [comment]
Thanks @mmermerkaya, we should be good to go, once we have the contributor licence agreement signed.

**Comment by mmermerkaya** [comment]
Thanks :) I'll do that as soon as I get approval from my employer (@google).

**Comment by mmermerkaya** [comment]
Yep, I've already emailed the relevant people. I'll ping this PR as soon as that's done.

**Comment by saschanaz** [comment]
IDBValidKey is not in the spec anymore, and the current dom.generated.d.ts does not have it. I think we should remove it completely.

**Pull request closed without merging**
