### PR TITLE
Expose webgl types to worker

### PR DESCRIPTION
**Pull request by saschanaz**
... as the spec is updated so.

### CODE REVIEW

**Comment by mhegazy** [comment]
//cc @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
@saschanaz what's going on with the Travis failures?

**Comment by saschanaz** [comment]
Ah, currently waiting https://github.com/KhronosGroup/WebGL/issues/2504. Sorry for the confusion!

**Comment by saschanaz** [comment]
Hi @RyanCavanaugh, I fixed the errors, assuming we have all extensions in worker environment. Can you review again?

**Pull request merged**
