### PR TITLE
Update `IDBDatabase` interface

### PR DESCRIPTION
**Pull request by falsandtru**
http://www.w3.org/TR/IndexedDB/#database-interface

### CODE REVIEW

**Comment by falsandtru** [comment]
ouch

**Comment by jasonwilliams200OK** [comment]
Is there any issue tracking this in TypeScript repo? A link to it would be nice.
This PR needs to be squashed to a single commit for multiple reasons. So:

```sh
cd TSJS-lib-generator
git rebase -i HEAD~4
# editor will open
# replace `pick` with `f`, for all lines except the first one, save and close the editor
git push -f
```

**Comment by falsandtru** [comment]
I didn't report this issue in TypeScript repo.

**Comment by mhegazy** [comment]
@falsandtru thanks for the PR, two comments:
1. please file an issue on the TS repo, this will allow for documenting the change.
2. do not change the webidl file directly, this file is external. put your changes in https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/overridingTypes.json instead.

**Comment by falsandtru** [comment]
All right, I'll fix it. And now, is there a way to fix webidl files?

**Comment by mhegazy** [comment]
The webidl files are external. we grab them periodically from the IE/Edge team. files `inputfiles/addedTypes.json`, `inputfiles/overridingTypes.json`, and `inputfiles/removedTypes.json` allow to augment the webidl definitions to get the desired shape. this way when a new version of the webidl is picked up the augmentations are not lost.

See [Readme.md](https://github.com/Microsoft/TSJS-lib-generator/blob/master/README.md#input-files) for more information.

**Comment by falsandtru** [comment]
I understood that. Thanks.

**Comment by falsandtru** [comment]
@mhegazy I filed a new issue: https://github.com/Microsoft/TypeScript/issues/6408, and I fixed your specified points. Please review, @mhegazy @zhengbli .

**Comment by falsandtru** [comment]
I have some unpublished fixes. I want to send that fixes after accepting this commit.

**Comment by mhegazy** [comment]
:+1:

**Comment by zhengbli** [comment]
@falsandtru Thank you for contributing!

**Pull request merged**
